import img1 from "../../assets/images/Clothes01.png";
import img2 from "../../assets/images/Clothes02.png";
import img3 from "../../assets/images/Clothes03.png";
import img4 from "../../assets/images/Clothes04.png";
import img5 from "../../assets/images/Clothes05.png";

export const items = [
  {
    id: 1,
    name: "아이엠 스튜디오 25 후드 라이트 그레이",
    price: 145000,
    review: 1561,
    rating: 4.6,
    gender: "남녀공용",
    color: "gray",
    size: "M",
    type: "의류",
    image: img1,
  },
  {
    id: 2,
    name: "아이엠 스튜디오 25 후드 라이트 블루",
    price: 145000,
    review: 1732,
    rating: 4.7,
    gender: "남성",
    color: "blue",
    size: "L",
    type: "의류",
    image: img2,
  },
  {
    id: 3,
    name: "아디다스 블랙 저지 2016",
    price: 255000,
    review: 781,
    rating: 4.5,
    gender: "남성",
    color: "black",
    size: "L",
    type: "의류",
    image: img3,
  },
  {
    id: 4,
    name: "슈프림 후드집업 30 딥블루",
    price: 458000,
    review: 2567,
    rating: 4.8,
    gender: "남녀공용",
    color: "denim",
    size: "XL",
    type: "의류",
    image: img4,
  },
  {
    id: 5,
    name: "나이키 에어 그레이 하운드 25",
    price: 235000,
    review: 231,
    rating: 4.4,
    gender: "남성",
    color: "gray",
    size: "10",
    type: "신발",
    image: img5,
  },
  {
    id: 6,
    name: "아이엠 스튜디오 25 후드 라이트 그레이",
    price: 145000,
    review: 1561,
    rating: 4.6,
    gender: "여성",
    color: "gray",
    size: "S",
    type: "의류",
    image: img1,
  },
  {
    id: 7,
    name: "아이엠 스튜디오 25 후드 라이트 블루",
    price: 145000,
    review: 1732,
    rating: 4.7,
    gender: "여성",
    color: "blue",
    size: "M",
    type: "의류",
    image: img2,
  },
  {
    id: 8,
    name: "아디다스 블랙 저지 2016",
    price: 255000,
    review: 781,
    rating: 4.5,
    gender: "남녀공용",
    color: "black",
    size: "M",
    type: "의류",
    image: img3,
  },
  {
    id: 9,
    name: "슈프림 후드집업 30 딥블루",
    price: 458000,
    review: 2567,
    rating: 4.8,
    gender: "여성",
    color: "multi",
    size: "XL",
    type: "의류",
    image: img4,
  },
  {
    id: 10,
    name: "나이키 에어 그레이 하운드 25",
    price: 235000,
    review: 231,
    rating: 4.4,
    gender: "여성",
    color: "gray",
    size: "9",
    type: "신발",
    image: img5,
  },];